--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Catalyst-Serendipity/MoreVanillaEnchantments
build-by-default: true
branches:
- main
projects:
  MoreVanillaEnchantments:
    path: ""
    icon: "assets/book.png"
    lint:
      phpstan: false
...
