name: MoreVanillaEnchantments
api: 5.12.0
version: 0.0.1-SNAPSHOT
main: serendipity\morevanillaenchantments\MoreVanillaEnchantments
author: Catalyst Serendipity Team
src-namespace-prefix: serendipity\morevanillaenchantments